# Generated by Django 5.2 on 2025-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('institution', 'Institution')], max_length=20)),
                ('password1', models.CharField()),
                ('password2', models.CharField()),
            ],
        ),
    ]
