# Generated by Django 5.2 on 2025-05-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
    ]
