# Generated by Django 5.2 on 2025-04-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options_A', models.CharField(max_length=500)),
                ('options_B', models.CharField(max_length=500)),
                ('options_C', models.CharField(max_length=500)),
                ('options_D', models.CharField(max_length=500)),
                ('is_correct', models.CharField(choices=[('options_A', 'Options A'), ('options_B', 'Options B'), ('options_C', 'Options C'), ('options_D', 'Options D')], max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz')),
            ],
        ),
    ]
