# Generated by Django 5.2 on 2025-04-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_usersanswer_quiz_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_useranswer',
            old_name='is_correct',
            new_name='is_selected',
        ),
    ]
