# Generated by Django 5.2 on 2025-04-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizsession_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
    ]
