# Generated by Django 5.2 on 2025-04-27 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_studentanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_question'),
            preserve_default=False,
        ),
    ]
