# Generated by Django 5.2 on 2025-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_studentanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
