# Generated by Django 5.2 on 2025-05-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='user',
        ),
    ]
