# Generated by Django 5.2 on 2025-05-04 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_quiz_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='avg_quiz_persentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='avg_quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='last_quiz',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='quiz_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
