# Generated by Django 5.2 on 2025-05-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_student_avg_quiz_correct_student_avg_quiz_persentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_quiz_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
