# Generated by Django 5.2 on 2025-05-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
