# Generated by Django 5.2 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_student_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_quiz',
            field=models.DateTimeField(null=True),
        ),
    ]
